import './style.css';
const arrow = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M4 12h15M13 5l7 7-7 7"/></svg>';
const walletIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="3" y="5" width="18" height="15" rx="3"/><path d="M3 8V5l14-3v3M16 11h5v5h-5z"/></svg>';
const networkIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M4 12h16M4 6h16M4 18h16"/></svg>';
interface Story {id:string; tag:string; title:string; subtitle:string; body:string; expandedBody:string; image:string; takeaway:string}
const stories:Story[] = [
{id:'city',tag:'THE BIG STORY',title:'The city is yours.\nTake it back.',subtitle:'Less traffic. More living. A new idea for the streets we share.',body:'Imagine the school run without the traffic jam. In our fictional city, a neighbourhood is trading through-traffic for trees, wider pavements and room to breathe. The big question: can a quieter street work for everyone?',expandedBody:'The change started small. One street closed to through-traffic on weekends. Then a second. Residents placed planters, painted hopscotch grids, set out folding chairs. Children learned to ride bikes without the roar of engines. An elderly neighbour, who hadn\'t crossed the road in years for fear of speeding cars, walked to the corner shop for the first time in a decade. The air quality sensors showed a measurable drop in nitrogen dioxide. Local businesses feared lost trade; instead, footfall increased as people lingered. The cafe spilled onto the pavement. A pop-up bookshop appeared in a reclaimed parking space. The council, initially sceptical, now fields requests from three more neighbourhoods. The model is spreading — not by mandate, but by example.\n\nWhat happened next surprised even the advocates. The street became a destination. People from neighbouring boroughs took the train to walk it. A documentary crew spent three weeks filming. The local primary school reported fewer asthma attacks. The GP surgery saw a drop in stress-related appointments. Property values on the street rose fifteen percent in eighteen months — but unlike the usual gentrification story, the original residents stayed. They\'d built something together, and they weren\'t leaving.\n\nThe councillor who opposed the trial now champions it. "I was wrong," she said at the town hall meeting. "I thought we were taking something away. We were giving something back." The street has a name now, unofficial but universal: Breathing Room. And every Sunday morning, when the barriers go up and the coffee cart arrives, you can hear it — the sound of a city remembering how to live.',image:'city-street',takeaway:'A better city starts at street level.'},
{id:'music',tag:'TURN IT UP',title:'Small stage.\nBig comeback.',subtitle:'The best night out might be just around the corner.',body:'A fictional community-run venue is putting local bands back in the spotlight. Its formula is refreshingly simple: affordable tickets, a tiny stage and a crowd that actually listens. Sometimes the next big thing needs a small room.',expandedBody:'The venue occupies a converted Victorian warehouse, its brick walls still bearing the ghost of industrial hooks. Capacity: eighty. No green room, no rider demands, no barrier between artist and audience. The booker, a former sound engineer, programmes by instinct — a folk trio on Tuesday, a noise-rock quartet on Friday, a jazz collective on Sunday. Musicians say the acoustics are honest; you hear every mistake, every moment of magic. The audience knows this. They lean in. Phones stay in pockets. Between sets, the bar serves local ales and the conversation flows across genres and generations. A teenager discovers their new favourite band; a retiree hears a sound that takes them back forty years. The venue runs on volunteers and a subscription model: members pay £5 a month for guaranteed entry, keeping tickets at £8 for everyone else. No venture capital. No algorithmic optimisation. Just rooms where music happens, and people show up for it. The waiting list for membership is six months long.\n\nLast month, a band who played their first gig here three years ago sold out the O2 Arena. They still come back for the anniversary show. The booker keeps a photo on the wall: four nervous kids with borrowed amps, grinning like they\'d won the lottery. "They asked for a rider once," she laughs. "A crate of lager and a packet of biscuits. We gave them the biscuits." The venue doesn\'t make stars. It makes musicians. And the audience? They get to say they were there when it started. That\'s the thing about small rooms — the history feels like yours.',image:'music-venue',takeaway:'Support acts deserve a little support.'},
{id:'sport',tag:'THE UNDERDOG',title:'All heart.\nNo superstars.',subtitle:'Meet the Sunday team playing for something bigger.',body:'Our imaginary neighbourhood club has a new rule: everyone gets a game. The results are mixed. The touchline is packed. And the post-match tea has never tasted better. Winning, it turns out, comes in more than one form.',expandedBody:'The rule was controversial at first. The striker who\'d scored thirty goals last season threatened to leave. The coach, a retired PE teacher, held firm: squad rotation, mandatory. Every player, regardless of ability, gets forty-five minutes. The league table suffered — they finished mid-table instead of challenging for promotion. But something else happened. The boy who\'d spent three seasons on the bench scored his first goal in November. His father wept on the touchline. The goalkeeper, sixty-three and playing since the club formed in 1978, made the save of the season in April. The opposition striker, twenty years younger, shook his hand afterwards. Attendance doubled. The clubhouse, once half-empty by half-time, now runs out of tea and cake before the final whistle. Local businesses sponsor the team not for exposure, but because it\'s theirs. The club doesn\'t produce professionals; it produces people who show up for each other, week after week, in rain and shine. The trophy cabinet is sparse. The community is full.\n\nThis season, the striker who threatened to leave came back. He apologised to the coach. He now runs the under-12s on Thursday evenings. The boy who scored his first goal? He\'s captain of the reserves. The sixty-three-year-old goalkeeper? Still playing. Still saving. Still shaking hands. The league table still doesn\'t matter. What matters is the Thursday night training where the first-team striker passes to the kid who once sat on the bench, and the kid passes back, and they both laugh. The club\'s motto, painted on the changing room wall: "Nobody sits out." It\'s not about football. It never was.',image:'sport-field',takeaway:'The best team is the one that makes room.'},
{id:'life',tag:'LIFE, A LITTLE BETTER',title:'Your lunch break\ncalled. Go out.',subtitle:'A small rebellion against another sandwich at your desk.',body:'For this sample story, an office tries a week of proper lunch breaks. No meetings. No inbox. Just twenty minutes outside. The verdict? The work was still there afterwards. So was a little more energy to do it.',expandedBody:'The experiment began with scepticism. Deadlines loomed. Slack channels buzzed. But the manager, inspired by a Swedish study on micro-breaks, declared a pilot: one week, proper lunch breaks, no exceptions. Monday was awkward — people stood in the park checking phones. By Wednesday, a rhythm emerged. A walking group formed, circling the square at varying paces. Someone brought a frisbee. Two colleagues discovered a shared love of birdwatching. The office plant, neglected for months, got watered daily. Productivity metrics, tracked quietly, didn\'t dip. Error rates on afternoon tasks fell twelve percent. Sick days dropped. The real change was subtler: conversations started crossing departmental lines. The designer learned the developer\'s dog\'s name. The finance lead discovered the intern wrote poetry. On Friday, the team voted unanimously to keep it. Not as policy — as practice. The sandwich at the desk became the exception, not the rule. Twenty minutes. That\'s all it took to remember they were human.\n\nSix months later, the walking group has a name and a WhatsApp chat with forty-seven members. The frisbee league has a trophy (a spray-painted mug). The birdwatchers have spotted forty-three species from the office roof. The intern published a chapbook; the finance lead wrote the foreword. The manager? She leaves at five now. Walks home through the park. Sees her team doing the same. The work is still there tomorrow. But so are they — lighter, sharper, connected. The sandwich at the desk was never the point. The point was remembering that the person across the desk is a person. Twenty minutes changed everything.',image:'lunch-break',takeaway:'Your screen will survive without you.'},
{id:'culture',tag:'OFF THE ALGORITHM',title:'Find your next\nfavourite. In person.',subtitle:'The record shop making discovery a human thing again.',body:'In our fictional shop, recommendations come on handwritten cards. No listening history required. Just tell the person behind the counter what you love, and trust them with the next three minutes. An old-school way to hear something new.',expandedBody:'The shop smells of vinyl dust and coffee. No screens behind the counter. The owner, a former session musician, knows every record by touch. You don\'t browse by genre — you browse by mood. "Something for a rainy Tuesday." "The album that got you through your breakup." "Music to cook to when you\'re not really hungry." She pulls three records, slides them across the counter with handwritten notes: "Start here. Then this. Trust me on the third." The listening station is a single chair, a pair of headphones, a turntable. No skip button. You listen to the whole side. People cry. People laugh. People buy records they\'d never have clicked on a playlist. The shop doesn\'t ship. No online store. You have to walk in. The queue on Saturday mornings stretches around the block. Regulars bring biscuits. Newcomers leave with arms full and ears ringing. The algorithm optimises for engagement; this place optimises for connection. The difference is everything.\n\nLast winter, a customer came in looking for "something hopeful." The owner handed him a 1973 folk record she\'d found in a clearance box. He listened. He bought it. He came back three weeks later with his daughter. "She needs to hear this," he said. The record became their thing — Sunday mornings, pancakes, side one, side two. He wrote the owner a note: "You didn\'t sell me a record. You gave me a morning with my daughter." The note is pinned behind the counter now, next to a hundred others. "You played the exact song I needed." "This album got me through chemo." "My grandfather had this record. I found it here." The algorithm knows what you\'ve listened to. The owner knows what you need. That\'s not data. That\'s care.',image:'record-shop',takeaway:'A little serendipity sounds good.'},
{id:'local',tag:'GOOD NEIGHBOURS',title:'Borrow a drill.\nBuild a community.',subtitle:'The little library lending everything except books.',body:'A make-believe library of things is helping neighbours share tools, camping gear and the occasional disco ball. Why buy something you need for one afternoon? Borrowing saves cupboard space — and gives you a reason to say hello.',expandedBody:'The library occupies a repurposed shipping container on the high street. Inside: a carpet cleaner, a pasta maker, a telescope, forty board games, a pressure washer, two tents, a sewing machine, a ukulele, and yes, a disco ball. Membership is free; you just bring something to share. A retired carpenter donated his planer. A student contributed her projector. The inventory grows by word of mouth. The borrowing log reads like a neighbourhood diary: "Mrs Chen — ladder — gutter cleaning." "The Ahmeds — tent — garden campout." "Jamal — sewing machine — prom dress alterations." "Disco ball — street party — the whole road came out." Items return cleaner than they left. People leave notes in the cases: "Works a treat — try the blue setting." "Great for beginners." The library doesn\'t just lend things; it makes visible the latent generosity of a street. The drill is the gateway. The conversation at the return desk is the point. Cupboards empty. Connections fill.\n\nTwo years in, the library has three containers and a waiting list for volunteers. The carpenter teaches woodworking on Saturdays. The student runs a film club using her projector. Mrs Chen\'s ladder helped paint the community centre. The Ahmeds\' tent hosted a refugee family\'s first Eid in the neighbourhood. Jamal\'s sewing machine made costumes for the school play. The disco ball? It spins every Friday at the youth club. The library doesn\'t track loans anymore — it tracks stories. The borrowing log is now a community archive. "Lent the pasta maker to the new neighbours. They made ravioli for the whole street." "Borrowed the telescope. Saw Saturn\'s rings. Cried a bit." The things are just things. The sharing is the infrastructure. The community is the product.',image:'tool-library',takeaway:'Less stuff. More connection.'},
{id:'weekend',tag:'THE SMALL ESCAPE',title:'Change your view.\nNot your postcode.',subtitle:'An adventure that starts at the next bus stop.',body:'Our sample weekend challenge has just three rules: take a route you have never taken, leave an hour unplanned, and stop somewhere that catches your eye. No airport queue. No grand itinerary. Curiosity is doing the heavy lifting.',expandedBody:'Saturday morning. The bus takes forty minutes instead of the usual twelve. You get off at a stop with no name you recognise. The high street has a bakery that\'s been there since 1923 — the sourdough still uses the original starter. You eat it standing by a canal you didn\'t know existed, watching a heron stand motionless as a statue. An hour unplanned becomes three. You wander into a churchyard where the gravestones tell the story of a cholera epidemic, a war, a family who lost three children in one week. An old man tending roses tells you the best view is from the hill behind the allotments. You climb. The city spreads below — not the postcard skyline, but the real one: washing lines, solar panels, a thousand tiny lives. You miss the last bus home. The night bus takes an hour. You don\'t mind. The week\'s stress has dissolved into something quieter. Monday morning, colleagues ask how your weekend was. You show them a photo of the heron. They lean in. You\'ve given them a map they didn\'t know they needed.\n\nThe challenge spread. The bakery now has a "Small Escape" board — handwritten notes from travellers. "Sat by the canal for two hours. Best therapy." "Found a vinyl shop in the arcade. Bought a record I\'ve hunted for years." "Met a man who knew my grandfather. He told me stories." The bus company noticed the ridership spike on the obscure routes. They added a weekend timetable. The old man at the allotments? He gives tours now. The heron? Still there. Still motionless. The city hasn\'t changed. You have. You know its corners now. Its secrets. Its Saturday mornings. Next weekend, you\'ll take a different bus. There\'s always another stop.',image:'bus-stop',takeaway:'You can be a tourist in your own town.'},
{id:'last',tag:'AND FINALLY…',title:'One more song.\nThen home. Promise.',subtitle:'A little joy is a perfectly good use of your time.',body:'The fictional neighbourhood disco was supposed to finish at nine. Then someone put on everyone\'s favourite song. We will spare you the debate about bedtimes. Sometimes the most important thing on your to-do list is a very bad dance.',expandedBody:'The hall smells of floor polish and spilled squash. The DJ — a parent volunteer with a questionable playlist — announces the last song. Three times. Each time, someone shouts "One more!" and the crowd roars. The headteacher attempts the worm. A toddler steals the mic. Two teenagers, too cool for everything five minutes ago, are screaming the lyrics to a song from 1987. The caretaker checks his watch, sighs, puts on "Don\'t Stop Me Now." The room erupts. Bedtimes are negotiated, extended, forgotten. Parents dance with their children, then with each other, then with strangers who feel like friends. The final song plays. The lights come up. No one moves. Someone starts singing a cappella. Others join. The caretaker turns the lights down again. The neighbourhood disco was supposed to finish at nine. It finishes when the last person stops smiling. That\'s not a time. That\'s a feeling. And it\'s the only deadline that matters.\n\nThe next morning, the WhatsApp group is full of blurry photos and voice notes. "My legs hurt." "Worth it." "Did you see Mrs Patel on the tables?" "The headteacher doing the worm will haunt me forever." The toddler who stole the mic? Asleep on the sofa, clutching a glitter microphone. The teenagers? Texting each other the playlist. The caretaker? Already planning next month\'s. The neighbourhood disco isn\'t an event. It\'s a reminder. That joy doesn\'t need a reason. That community isn\'t built on grand gestures but on bad dancing and shared lyrics and the courage to look foolish together. The hall will be empty by noon. The glitter will take weeks to vacuum. The feeling? That stays. That\'s the point.',image:'disco',takeaway:'That\'s your cue. Have a good day.'}
];

interface Publication {
  id: string;
  name: string;
  subtitle: string;
  storyOrder: number[];
  color: string;
  accent: string;
}
const publications:Publication[] = [
  {id:'the-point',name:'the point',subtitle:'A LITTLE PERSPECTIVE. EVERY DAY.',storyOrder:[0,1,2,3,4,5,6,7],color:'#1a2018',accent:'#d5fa44'},
  {id:'touchline',name:'touchline.',subtitle:'BEYOND THE FINAL WHISTLE.',storyOrder:[2,0,5,3,7,1,4,6],color:'#1a1d22',accent:'#44b8fa'},
  {id:'afterhours',name:'afterhours',subtitle:'CULTURE WORTH STAYING UP FOR.',storyOrder:[1,4,6,3,0,7,5,2],color:'#221a22',accent:'#d3b0ff'},
  {id:'pulse',name:'pulse',subtitle:'THE CITY\'S HEARTBEAT.',storyOrder:[3,5,0,7,2,6,1,4],color:'#221a18',accent:'#fa8844'},
];

interface State {paid:boolean;balance:number;position:number;visited:string[];reward:boolean;screen:'cover'|'reader'|'complete'|'network';expanded:string[];publication:string}
const fresh=():State=>({paid:false,balance:100,position:0,visited:[],reward:false,screen:'cover',expanded:[],publication:'the-point'});
const key='the-point-demo-v2';
function restore():State {try{const s=JSON.parse(sessionStorage.getItem(key)||'null');if(s && typeof s.paid==='boolean' && typeof s.reward==='boolean' && Number.isInteger(s.position) && s.position>=0 && s.position<=8 && Array.isArray(s.visited) && Array.isArray(s.expanded) && ['cover','reader','complete','network'].includes(s.screen) && publications.some(p=>p.id===s.publication)){s.balance=100-(s.paid?20:0)+(s.reward?10:0);if(!s.paid)return fresh();if(s.screen==='complete'&&new Set(s.visited).size!==8)s.screen='reader';return s;}}catch{}return fresh();}
let state=restore();
const app=document.querySelector<HTMLDivElement>('#app')!; const sheet=document.querySelector<HTMLDialogElement>('#sheet')!;
const money=(n:number)=>`£${(n/100).toFixed(2)}`;
function save(){try{sessionStorage.setItem(key,JSON.stringify(state));}catch{}}
function notify(message:string){const t=document.querySelector<HTMLDivElement>('#toast')!;t.textContent=message;t.classList.add('visible');window.setTimeout(()=>t.classList.remove('visible'),3000);}
function logo(){return '<span class="logo">the point<span>.</span></span>';}
function currentPub(){return publications.find(p=>p.id===state.publication)!;}
function getStories(){return currentPub().storyOrder.map(i=>stories[i]);}
function storyIndex(){return state.position>4?state.position-1:state.position;}
function mark(){if(state.screen==='reader'&&state.position!==4){const s=getStories();const id=s[storyIndex()]?.id;if(id && !state.visited.includes(id))state.visited.push(id);}save();}
function render(){mark();const isCover=state.screen==='cover';const isNetwork=state.screen==='network';const pub=currentPub();
if(isNetwork){renderNetwork();return;}
app.innerHTML=`<header class="site-header"><button class="brand-button" data-action="home" aria-label="The Point home"><span class="logo">${pub.name}<span style="color:${pub.accent}">.</span></span></button><span class="header-edition">${pub.subtitle}</span><button class="wallet-button" data-action="wallet">${walletIcon}<span>${money(state.balance)}</span><span class="demo-tag">DEMO</span></button></header><button class="network-up" data-action="network" aria-label="Browse the Point network">${networkIcon} THE POINT NETWORK</button><main class="stage ${isCover?'cover-stage':''}"><aside class="side-note"><span class="vertical-line"></span><span>YOUR DAILY DOSE OF PERSPECTIVE</span></aside><section class="reader ${isCover?'cover':''}" aria-label="Daily edition">${isCover?cover():state.screen==='complete'?complete():reader()}</section><aside class="desktop-nav">${state.screen==='reader'?`<button class="round" data-action="next" aria-label="${state.position===8?'Finish edition':'Next story'}">${arrow}</button><span>${state.position===4?'A LITTLE BREAK':`${String(storyIndex()+1).padStart(2,'0')} / 08`}</span><button class="round back" data-action="prev" aria-label="Previous story">${arrow}</button>`:'<span class="edition-mark">01<br><small>THE DAILY<br>EDITION</small></span>'}</aside></main><footer class="site-footer"><span>INDEPENDENT MINDS. A SHARED WORLD.</span><span>Sample edition · Fictional stories</span><button data-action="network">Browse network ${arrow}</button></footer>`;setupScrollExpand();}
function renderNetwork(){
app.innerHTML=`<header class="site-header"><button class="brand-button" data-action="home" aria-label="The Point home"><span class="logo">the point<span>.</span></span></button><span class="header-edition">THE POINT NETWORK</span><button class="wallet-button" data-action="wallet">${walletIcon}<span>${money(state.balance)}</span><span class="demo-tag">DEMO</span></button></header><main class="stage network-stage"><div class="network-grid">${publications.map(p=>`<button class="network-card" data-action="select-pub" data-pub="${p.id}" style="border-color:${p.accent}30;background:${p.color}"><div class="network-card-accent" style="background:${p.accent}"></div><h2 class="network-card-title" style="color:${p.accent}">${p.name}<span>.</span></h2><p class="network-card-sub">${p.subtitle}</p><div class="network-card-preview">${p.storyOrder.slice(0,3).map(i=>`<span class="network-card-tag">${stories[i].tag}</span>`).join('')}</div><span class="network-card-arrow">${arrow}</span></button>`).join('')}</div></main><footer class="site-footer"><span>INDEPENDENT MINDS. A SHARED WORLD.</span><span>Sample edition · Fictional stories</span><button data-action="home">Back to The Point ${arrow}</button></footer>`;}
function cover(){const pub=currentPub();return `<img class="cover-image" src="/images/cover-main.jpg" alt="London and the River Thames at dusk" loading="eager" data-load="fade"><div class="image-shade"></div><div class="cover-top"><span class="pill" style="background:${pub.accent}22;border-color:${pub.accent}55"><i style="background:${pub.accent}"></i> ${pub.subtitle}</span><span>WED, 16 SEP 2026</span></div><div class="cover-content"><div class="eyebrow" style="color:${pub.accent}">THE BIG STORY <span>01 — 08</span></div><h1>The city<br>is yours.<br><em style="color:${pub.accent}">Take it back.</em></h1><p>Less traffic. More living.<br>A new idea for the streets we share.</p><div class="cover-bottom"><div class="edition-info"><span class="mini-bars" style="color:${pub.accent}">▥</span><span>8 stories. One daily edition.</span><span>~ 5 MIN</span></div><button class="primary" data-action="start" style="background:${pub.accent}">${state.paid?'Continue reading':'Read today — 20p'} ${arrow}</button><div class="payment-note">One edition. One small price. <span>Powered by <b>axate</b></span></div></div></div>`;}
function reader(){const ad=state.position===4;const s=getStories()[storyIndex()];const isExpanded=state.expanded.includes(s?.id||'');const pub=currentPub();return `<img class="story-image" src="/images/${ad?'sponsored':s.image}.jpg" alt="${ad?'Sponsored content':s.title}" loading="eager" data-load="fade"><div class="image-shade"></div><div class="reader-top"><div class="progress" aria-label="${state.visited.length} of 8 stories visited">${getStories().map((st,i)=>`<span class="${state.visited.includes(st.id)?'seen':''} ${!ad&&i===storyIndex()?'active':''}" style="${!ad&&i===storyIndex()?`background:${pub.accent}`:''}"></span>`).join('')}</div><div class="reader-meta"><button data-action="home" aria-label="Back to front page"><span class="logo">${pub.name}<span style="color:${pub.accent}">.</span></span></button><span>${ad?'PARTNER MOMENT':`${String(storyIndex()+1).padStart(2,'0')} / 08`}</span></div></div>${ad?`<article class="story-content sponsored"><span class="pill">SPONSORED · DEMO PARTNER</span><div class="partner-name">ENCORE<span>®</span></div><h1>Good nights.<br><em>Good rewards.</em></h1><p>Your next great night starts with a little something back. Enjoy 10p on us, straight to your demo wallet.</p><button class="primary" data-action="claim" ${state.reward?'disabled':''} style="background:${pub.accent}">${state.reward?'✓ 10p added to your wallet':'Claim your 10p reward'} ${state.reward?'':arrow}</button><small>A fictional partner. A simulated reward. No purchase needed.</small></article>`:`<article class="story-content ${isExpanded?'expanded':''}" data-story-id="${s.id}"><div class="eyebrow" style="color:${pub.accent}">${s.tag}<span>${pub.name.toUpperCase()}</span></div><h1>${s.title.replace('\n','<br>')}</h1><p class="standfirst">${s.subtitle}</p><p class="body-copy">${isExpanded?s.expandedBody:s.body}</p>${!isExpanded?`<button class="expand-button" data-action="expand" data-story="${s.id}" style="border-color:${pub.accent}40">Read more ${arrow}</button>`:''}<div class="takeaway" style="border-color:${pub.accent}30"><span style="color:${pub.accent}">THE POINT?</span><p>${s.takeaway}</p></div></article>`}<nav class="story-nav" aria-label="Story navigation"><button data-action="prev" aria-label="Previous story">${arrow}</button><span>${ad?'A little thank you for reading.':'SWIPE FOR A LITTLE MORE PERSPECTIVE'}</span><button data-action="next" aria-label="${ad?'Skip sponsored card':state.position===8?'Finish edition':'Next story'}">${arrow}</button></nav>`;}
function complete(){const pub=currentPub();return `<div class="completion"><div class="eyebrow" style="color:${pub.accent}">THE DAILY EDITION <span>08 / 08</span></div><div class="complete-symbol" style="background:${pub.accent}">✓</div><span class="eyebrow">AND THAT'S THE POINT.</span><h1>You're<br>up to date<span style="color:${pub.accent}">.</span></h1><p>Eight stories. A fresh perspective.<br>The rest of the day is yours.</p><div class="stats"><div><strong>8 / 8</strong><span>STORIES READ</span></div><div><strong>${state.reward?'10p':'0p'}</strong><span>REWARDS EARNED</span></div></div><button class="primary" data-action="again" style="background:${pub.accent}">Read again ${arrow}</button><div class="network-heading">A LITTLE MORE YOUR THING <span>↗</span></div><div class="network"><button data-action="network"><b>touchline<span>.</span></b><span>Beyond the final whistle ↗</span></button><button data-action="network"><b>afterhours<span>✳</span></b><span>Culture worth staying up for ↗</span></button></div><small>Sample titles from the Point network</small></div>`;}
function openSheet(kind:string){const payment=kind==='payment';sheet.innerHTML=`<div class="sheet-handle"></div><button class="close" data-action="close" aria-label="Close dialog">×</button>${kind==='touchline'||kind==='afterhours'?`<span class="eyebrow">THE POINT NETWORK · PREVIEW</span><h2>${kind==='touchline'?'touchline.':'afterhours'}</h2><p>${kind==='touchline'?'For the stories behind the score. Players, people and the beautiful unpredictability of sport.':'Your backstage pass to music, film and the things everyone will be talking about tomorrow.'}</p><div class="preview-story"><span>SAMPLE STORY</span><h3>${kind==='touchline'?'The club that belongs to its fans.':'Small rooms. Unforgettable nights.'}</h3></div><p class="fine-print">This is a preview of a fictional network title.</p><button class="primary" data-action="close">Back to The Point ${arrow}</button>`:`<span class="eyebrow">YOUR AXATE WALLET</span><h2>${payment?'A little price.<br>A whole new perspective.':'Small change.<br>Good stories.'}</h2><p>${payment?'Unlock all eight stories in today\'s edition with one simple payment.':'Your demo funds travel with you across The Point.'}</p><div class="balance-row"><span>Demo balance</span><strong>${money(state.balance)}</strong></div>${payment?'<div class="price-row"><span>Today\'s edition</span><strong>20p</strong></div><button class="primary" data-action="pay">Pay 20p & start reading ${arrow}</button><button class="text-button" data-action="close">Not right now</button>':`<div class="price-row"><span>Today\'s edition</span><span>${state.paid?'20p paid':'Not yet unlocked'}</span></div><div class="price-row"><span>Partner reward</span><span>${state.reward?'+10p received':'Not yet claimed'}</span></div>`}<p class="fine-print">Demo funds only. No real money or payment details.<br>Powered by <b>axate</b></p>`}`;sheet.setAttribute('aria-label',payment?'Unlock today\'s edition':kind==='wallet'?'Demo wallet':'Network title preview');sheet.showModal();}
function move(delta:number){if(state.screen!=='reader')return;if(delta<0&&state.position===0){state.screen='cover';}else if(delta>0&&state.position===8){if(state.visited.length===8)state.screen='complete';else {const s=getStories();const missing=s.findIndex(st=>!state.visited.includes(st.id));state.position=missing>=4?missing+1:missing;}}else state.position=Math.max(0,Math.min(8,state.position+delta));render();document.querySelector<HTMLElement>('.reader')?.scrollTo(0,0);}
function action(name:string,title?:string,pubId?:string){switch(name){case 'home':state.screen='cover';state.position=0;render();break;case 'network':state.screen='network';render();break;case 'select-pub':if(pubId && pubId!==state.publication){state.publication=pubId;state.position=0;state.screen='reader';state.expanded=[];save();render();}break;case 'start':if(state.paid){state.screen='reader';render();}else openSheet('payment');break;case 'wallet':openSheet('wallet');break;case 'close':sheet.close();break;case 'pay':if(!state.paid){state.paid=true;state.balance-=20;}sheet.close();state.screen='reader';render();notify('You\'re in. Today\'s edition is yours.');break;case 'next':move(1);break;case 'prev':move(-1);break;case 'claim':if(state.paid&&state.position===4&&!state.reward){state.reward=true;state.balance+=10;render();notify('10p added to your demo wallet. Nice.');}break;case 'expand':if(title && !state.expanded.includes(title)){state.expanded.push(title);save();render();document.querySelector<HTMLElement>('.reader')?.scrollTo(0,0);}break;case 'again':state.position=0;state.screen='reader';render();break;case 'reset':sheet.close();state=fresh();render();notify('Fresh edition. Demo wallet reset to £1.00.');break;case 'preview':openSheet(title!);break;}}
document.addEventListener('click',e=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('button[data-action]');if(button&&!button.disabled){const focused=button.dataset.action;action(focused!,button.dataset.title||button.dataset.story,button.dataset.pub);if(!sheet.open&&focused&&['next','prev','claim','start','pay','again'].includes(focused)){const target=document.querySelector<HTMLButtonElement>(`button[data-action="${focused}"]`)||document.querySelector<HTMLButtonElement>('button[data-action="next"]');target?.focus({preventScroll:true});}}});
sheet.addEventListener('click',e=>{if(e.target===sheet){const r=sheet.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)sheet.close();}});
document.addEventListener('keydown',e=>{if(sheet.open||state.screen!=='reader')return;if(e.key==='ArrowRight'){e.preventDefault();move(1);}if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}if(e.key==='ArrowUp'&&(window.scrollY<=0)){e.preventDefault();state.screen='network';render();}});
let startX=0,startY=0;app.addEventListener('touchstart',e=>{startX=e.touches[0].clientX;startY=e.touches[0].clientY;},{passive:true});app.addEventListener('touchend',e=>{if(sheet.open)return;const dx=e.changedTouches[0].clientX-startX,dy=e.changedTouches[0].clientY-startY;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5)move(dx<0?1:-1);else if(dy<-70&&Math.abs(dy)>Math.abs(dx)*1.5&&window.scrollY<=0&&document.querySelector<HTMLElement>('.reader')?.scrollTop===0){state.screen='network';render();}},{passive:true});

function setupScrollExpand(){const readerEl=document.querySelector<HTMLElement>('.reader')!;const article=readerEl.querySelector<HTMLElement>('article.story-content:not(.sponsored)');if(!article)return;const storyId=article.dataset.storyId;if(!storyId||state.expanded.includes(storyId))return;let ticking=false;function onScroll(){if(ticking)return;ticking=true;requestAnimationFrame(()=>{const rect=article!.getBoundingClientRect();const readerRect=readerEl.getBoundingClientRect();if((article as HTMLElement).getBoundingClientRect().bottom>readerRect.bottom-100&&!state.expanded.includes(storyId!)){state.expanded.push(storyId!);save();render();}ticking=false;});}readerEl.addEventListener('scroll',onScroll,{passive:true});readerEl.querySelectorAll<HTMLImageElement>('img[data-load="fade"]').forEach((img:HTMLImageElement)=>{if(img.complete)img.classList.add('loaded');else img.addEventListener('load',()=>img.classList.add('loaded'),{once:true});});}

render();

interface ModelContext {registerTool(tool:{name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown}):void|Promise<void>}
const modelContext=(document as Document & {modelContext?:ModelContext}).modelContext;
if(modelContext){
  const tools=[
    {name:'read_demo_edition',description:'Read the current fictional edition progress and simulated wallet balance.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...state,visited:[...state.visited]})},
    {name:'navigate_demo_story',description:'Move to the next or previous story in an already unlocked demo edition. Does not make a payment.',inputSchema:{type:'object',properties:{direction:{type:'string',enum:['next','previous']}},required:['direction'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const value=input as {direction?:unknown};if(!value||!['next','previous'].includes(String(value.direction)))throw new Error('Direction must be next or previous');if(!state.paid||state.screen!=='reader')throw new Error('Open an unlocked edition first');move(value.direction==='next'?1:-1);return {screen:state.screen,position:state.position,visited:state.visited.length};}}
  ];
  for(const tool of tools){try{Promise.resolve(modelContext.registerTool(tool)).catch(()=>{});}catch{}}
}